### PR TITLE
added a better ldap handling, and to allow query active directory

### PR DESCRIPTION
**Pull request by mabels**
I added the ldap handling so that it could work now with e.g. activedirectory.

The pam line should look like this
auth  required       pam_yubico.so ldap_uri=ldap://ldap debug id=19 yubi_attr=pager ldapdn=dc=ad,dc=adviser,dc=com ldap_bind_user=cn=openvpn,cn=Users,dc=ad,dc=adviser,dc=com ldap_bind_password=dsjgjgfdgdger ldap_filter=(sAMAccountName=%u)

### CODE REVIEW

**Comment by mabels** [comment]
Hey,

is there any hope that you integrate my stuff?

thx in advance

meno

**Comment by klali** [comment]
Hello,

We're in principle positive to merge this, however:
I'd like us to have some tests hitting the ldap code before merging. I've added some tests of the actual pam functions on a branch and want to add something that can hit the ldap code as well (feel free to contribute code or ideas towards that goal).

/klas

**Comment by mabels** [comment]
Hello Klas,

i will try to mock the ldap commands somehow to have some tests. I totally
understand that you and I want's some tests but mocking in c could be hard
somehow. I will try something-:) on the next weekend

cheers

meno

**Comment by klali** [comment]
There is now a start of a ldap mock on the master branch in tests/aux/ldap.pl it's simplistic and doesn't know about alot of stuff yet..

**Comment by mabels** [comment]
@ctucker1963 i will add these to the supported features-:)
but i'm still have no time to complete the tests-:(

**Comment by klali** [comment]
On the matter of spaces in the options list..
the options list is parsed by the system pam library, and pam.conf(5) says:
"Note, if you wish to include spaces in an argument, you should surround that argument with square brackets."
could you try that @ctucker1963 ?

**Comment by ctucker1963** [comment]
@klali Thank you, I'll give the square brackets a try. I'll let you know how it works.

**Comment by ctucker1963** [comment]
@klali Yes indeed! The square bracket trick does work. Thank you.

**Comment by ctucker1963** [comment]
@mabels Thank you for you reply too. I've noticed that it might be better to store key mappings in a multi-value string attribute like otherPager as opposed to pager. This would allow for mapping of multiple IDs to one user as can be done through a client mapping file.

**Comment by ctucker1963** [comment]
@klali @mabels So I took some time to tinker with a copy of pam_yubico.c and compile it. 
I made modifications to the authorize_user_token_ldap function in pam_yubico.c which would allow the LDAP search (ldap_search_ext_s) to find a user object in sub-OUs of the specified ldapdn PAM module option. 
We need this as our yubikey users will be scattered in various different OUs and sub-OUs. I've tested this modification against our Active Directory environment (LDAP) and so far so good.
I'm a newby to this forum so I don't know if this is the appropriate location to display the changes I made. Nor am I familiar with which format they should be displayed here. But I'll post them if you are interested.
Cheers!

**Comment by mabels** [comment]
hey you could fork my github repro apply the changes and post a pull
request to me.
Or you just past here a small patch in i will then try to integrate it.

thx in advance

**Comment by ctucker1963** [comment]
Sorry, Ill have to talk to our GIT expert to help me out in doing that. I'll get back to you soon.

**Comment by mabels** [comment]
git diff  and send me the output.

meno

**Comment by ctucker1963** [comment]
@mabels very good, I hope that this makes sense.

diff --git a/pam_yubico.c b/pam_yubico.c
index 77f0e86..0a1bf81 100644
--- a/pam_yubico.c
+++ b/pam_yubico.c
@@ -222,6 +222,8 @@ authorize_user_token_ldap (struct cfg *cfg,
   int i, rc;
 
   char *find = NULL;
+  char *base = NULL;
+  char *filter = NULL;
 #endif
   DBG(("called"));
 #ifdef HAVE_LIBLDAP
@@ -281,15 +283,31 @@ authorize_user_token_ldap (struct cfg *cfg,
     goto done;
   }
 
+  i = (strlen(cfg->ldapdn) + 3) * sizeof(char);
+  if ((base = malloc(i)) == NULL) {
+    DBG (("Failed allocating %i bytes", i));
+    retval = 0;
+    goto done;
+  }
+
+  i = (strlen(cfg->user_attr) + strlen(user) + 6) * sizeof(char);
+  if ((filter = malloc(i)) == NULL) {
+    DBG (("Failed allocating %i bytes", i));
+    retval = 0;
+    goto done;
+  }
+
   sprintf (find, "%s=%s,%s", cfg->user_attr, user, cfg->ldapdn);
+  sprintf (base, "%s", cfg->ldapdn);
+  sprintf (filter, "%s=%s", cfg->user_attr, user);
 
   attrs[0] = (char *) cfg->yubi_attr;
 
-  DBG(("LDAP : look up object '%s', ask for attribute '%s'", find, cfg->yubi_attr));
+  DBG(("LDAP : look up object '%s', ask for attribute '%s'", filter, cfg->yubi_attr));
 
   /* Search for the entry. */
-  if ((rc = ldap_search_ext_s (ld, find, LDAP_SCOPE_BASE,
-                              NULL, attrs, 0, NULL, NULL, LDAP_NO_LIMIT,
+  if ((rc = ldap_search_ext_s (ld, base, LDAP_SCOPE_SUBTREE,
+                              filter, attrs, 0, NULL, NULL, LDAP_NO_LIMIT,
                               LDAP_NO_LIMIT, &result)) != LDAP_SUCCESS)
     {
       DBG (("ldap_search_ext_s: %s", ldap_err2string (rc)));
@@ -350,6 +368,10 @@ authorize_user_token_ldap (struct cfg *cfg,
   /* free memory allocated for search strings */
   if (find != NULL)
     free(find);
+  if (base != NULL)
+    free(base);
+  if (filter != NULL)
+    free(filter);
 
 #else
   DBG (("Trying to use LDAP, but this function is not compiled in pam_yubico!!"));

**Comment by mabels** [comment]
@ctucker1963

thx for the patch but it looks like that you used the upstream version from
these
https://github.com/Yubico/yubico-pam
to make your extention this is not matching to my prev change which is
pending for integration
out of the fact of missing tests. I think I tailored all your requested
features in my version that is avail.
from
https://github.com/mabels/yubico-pam
it would be wunderfull if you retest and use my version.

thx meno

**Comment by mabels** [comment]
Hey we are working on the same thing but with different solutions. You try to build a extern small ldap server. I just build a "virtual" internal ldap abstraction to the common ldap library. I thing both approaches are feasable but we should decide which one is the better one. I used my approach to mock also pam and ykclient so there are two more internal mocked api's. 
I think for pam there is only the internal solution possible.
I will complete my ldap internal and than you could decide where to go.

Cheers

meno

**Comment by klali** [comment]
Right now I'm leaning in the direction of my mocks, as they don't require modification of the original at all and still uses the original dependency.
The ldap mock requires a bit more work to be run for more cases..

**Comment by mabels** [comment]
Right it is a compromise. Did you looked in my source, I done it very thin
for LDAP and ykclient, there is no new dependcy the only change I done is
to prefix the related function calls. I could remove the prefixed calls but
this could lead to in transparency.
For the Pam stuff I link a different Pam lib against the test programm.

Meno

**Comment by mabels** [comment]
hey,

i just pushed, a working test without any external interface need, runable
as non root on my mac, keep in mind that the rra-c-util is not  completed
yet.

The ldap mock is only less then 5lines of code + boilerplat stuff.
So please have a look, i will fix the build system next.

cheers

meno

**Comment by kai1074** [comment]
Hello Meno, 
I'm trying to build on Ubuntu 14.04, and I get these errors:
  CC       yubi_ldap.lo
yubi_ldap.c:35:4: error: 'ldap_init' undeclared here (not in a function)
   &ldap_init,
    ^
yubi_ldap.c:38:4: error: 'ldap_simple_bind_s' undeclared here (not in a function)
   &ldap_simple_bind_s,
    ^
yubi_ldap.c:48:4: error: 'ldap_unbind_s' undeclared here (not in a function)
   &ldap_unbind_s,
    ^

At a very very quick look into ldap libraries, it seems those functions are deprecated:

/usr/include/ldap.h:ldap_init LDAP_P(( /* deprecated, use ldap_create or ldap_initialize */
/usr/include/ldap.h:ldap_simple_bind_s LDAP_P(( /* deprecated, use ldap_sasl_bind_s */
/usr/include/ldap.h:ldap_unbind_s LDAP_P(( /* deprecated, use ldap_unbind_ext_s */

I'd need to test your version of pam-yubico only for dn subtree search, is there a way to overcome this problem?

Thank you very much!
Stefano

**Comment by mabels** [comment]
I do a test on soon

Meno

**Comment by mabels** [comment]
I fixed some stuff, and remove the rrtc pam dependcy.
I only not done real tests with a pam module and ldap enabled
i will go there tomorrow.

cheers

meno

**Comment by mabels** [comment]
Hey, 

i tested with the su command, and discovered that, i need to ask for the users password if there
is no user provided for the ldap bind. I will add this to the pam-module soon. It will take at least 
a week. My test infrastructur is pretty nice working now.

**Comment by klali** [comment]
I'd like to get this merged as minimal as possible before adding more features to it. The more complex it gets the harder it is to merge.
I've been looking a little bit at merging from aa87979eb84adb3adef170dac6ff2285ba43cd26

If the integration of #39 is just to make them compatible I think we can drop that, we don't need more parameters for their own sake (binddn, bindpw)

Do we need the implementation of pam_sm_acct_mgmt() ? In that case I'd like it to not be for only ldap, but generic checking if auth was ok.
Same question for pam_sm_open_session(), pam_sm_close_session() & pam_sm_chauthtok() do we need them?

I'm a bit scared about the filter_result_len() logic in util.c it'd be nice to make this simpler. Do you see a usecase where there is a need to insert the username more than once into the filter? If not we might rely on the filter being a standard format string and using snprintf() to insert the username.

**Comment by mabels** [comment]
I'm agree with not adding more features, but my tests shown the pam module
is not working with a simple
login, if i enable my ldap extention. The new feature is small

in pam_yubikey.
  else
    password = NULL;

  rc = v_ykclient_request (ykc, otp);

here i have to ask for the users password.

#39 i remove the compatibly if you want to

the pam_sm... methods are need if you ran it with openvpn for example. If
you want to have no users on the
system only the users from ldap than you need fullfill these dummys to make
the openvpn pam module happy.

The double username could sence full if you generated complex ldap querys.
I have no example , i wrote
the tests to get these code confident for me. So i trust me-:) it's only 20
lines, which could be done with
strtok and alot more handle of dynamic allocated memory-:(
I thing currently on 'u' is supported but there should be a y(for the key
id) or a o(for the otp) possible, and than
we need such a code either.

could you give me a hint how "you" format your code. Sometimes there are
tabs sometimes spaces how much
space is a tab. Sometimes this look stranges and i'm also not clean with
this.

Meno

**Comment by klali** [comment]
You mean for the case of ldap_bind_user_filter? I think it's better to rely on use_first_pass/try_first_pass to get that password.. Alternatively considering other ways to bind (sasl-gssapi with a keytab or using the users TGT from earlier authentication..)

The formatting is inconsistent, we try to keep it inline with the surrounding code.

**Comment by mabels** [comment]
Yes it is in the ldap_bind_user_filter case.
I just write the testcases to figure out what is broken and than fixit with
the most little effort. The use_first_pass/try_first_pass
stuff is based on the basic principle you provide the password + otp in one
step.
But this is not all time the case, if you add the pam module to the
standard login it pretty cool to see that the graphical login
ask you in to steps about your password and the yubikey.
BTW where you are working(city), i just have some days off and looking for
a place to go and meet and work with some
nice people?

cheers
meno

**Comment by klali** [comment]
Makes me a bit wary about including ldap_bind_user_filter at all, not to keen on sending the users password out in another direction.

For me this PR is about a couple of things:
* changing so a filter can be used for finding correct objects (and subtree)
* adding dn + password for authenticated bind
* doing bind with the users credentials
* compatibility with openvpn by implementing more functions
* add ldap_cacertfile

Unfortunately it's a bit hard to merge since we're doing so many things at once.

I'm not sure what the option ldap_bind_no_anonymous achieves, is there any hope of that working without also using ldap_bind_user_filter ?

I don't think we have any possibilities of inviting you to work from our office, sorry.

**Comment by mabels** [comment]
Where is in ldap_bind_user_filter any reference to the users password.
Currently there is only the username involved. But the multiple %u could be
fine for looking up the user in two subtrees or something like that. Which
could make some sence in the terms of the strange groups in ldap at all.

ldap_bind_no_anonymous this flag controlls if the ldap_bind is done with a
fixed predefined user or with the users supplied password. The no in the
name
is out of the fact we hat the predefined thing before my change.

Could you somehow give me example where we are working on the same stuff so
that the merging gets difficult?

I only added the v_ methods all around, nothing else is global on my
change. So any conflict should be solvable easy by using your code and put
the v_ in it.

Thx

meno

**Comment by mabels** [comment]
Hey on wikipedia is a good example that multiple %u could be usefull

(&(objectClass=person)(|(givenName:caseExactMatch:=John)(mail:caseExactSubstringsMatch:=john*)))

FYI Meno

**Comment by klali** [comment]
I'm currently on my way to merge parts of your pull request (at aa87979eb84adb3adef170dac6ff2285ba43cd26) which would add authenticated bind (with user and pw in config) and subtree search with filter.

We can then continue the discussion of more advanced features.

**Comment by mabels** [comment]
Hey

I'm currently hard working on the preparation to a job interview. but I
started a refactoring two weeks ago. the refactoring is not completed yet.
I will continue tomorrow on it.
i would recommended to wait until wedsenday with the merge

thx in advance

meno

**Comment by mabels** [comment]
Just completed my refactoring. Merge with your master just now. 
Everything looks pretty cool now.

I think this is a good point now. Read my last commit msg, there is a quiet precise description what i did in today.

**Comment by klali** [comment]
I've merged parts of this to a new branch feature/ldap_refactor with some additional work. IMO it would be useful to get those parts merged and then continue the discussion around more advanced features.

**Comment by mabels** [comment]
i with you, means it will stop for now,
what is your additional work? i did have a look to the merged result.

meno

**Comment by klali** [comment]
additional work on that is mostly minor things, noteworthy difference from aa87979eb84adb3adef170dac6ff2285ba43cd26 is done in 5709a4479a77408b92977fc46ff6d63e5aa54189 where I've backed out the ldap_bind_no_anonymous feature.

**Comment by klali** [comment]
I'd like to close this pull request now as we've accomplished to get parts of it in. I'm happy to continue discussion around additional features, but in new pull requests/issues.

Thank you for the contributions @mabels!

/klas
